### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bnoffer** [OneSignal/OneSignal-DotNet-SDK#59]
### What happened?

When hard-closing the App on the iOS simulator the following exception is thrown:
`Cannot get the method descriptor for the selector 'oneSignalApplicationWillTerminate:' on the type 'myapp.AppDelegate', because the selector does not correspond to a method (ObjCRuntime.RuntimeException)`

### Steps to reproduce?

```Markdown
1. Install v. 4.3.3 of the Package on .NET MAUI 7.0.92
2. Initialize the SDK according to documentation
3. Start the App in Simulator
4. Hard-close the App
```

### What did you expect to happen?

The app to close cleanly

### Relevant log output

```Shell
2023-07-14 12:23:24.036283+0200 myapp[17631:3706642] Unhandled managed exception: Failed to lookup the required marshalling information.
Additional information:
	Selector: oneSignalApplicationWillTerminate:
	Type: AppDelegate
 (ObjCRuntime.RuntimeException)
   at UIKit.UIApplication.UIApplicationMain(Int32 argc, String[] argv, IntPtr principalClassName, IntPtr delegateClassName)
   at UIKit.UIApplication.Main(String[] args, Type principalClass, Type delegateClass)
   at myapp.Program.Main(String[] args) in /Users/ban/Projects/myapp/myapp/Platforms/iOS/Program.cs:line 13
Cannot get the method descriptor for the selector 'oneSignalApplicationWillTerminate:' on the type 'myapp.AppDelegate', because the selector does not correspond to a method (ObjCRuntime.RuntimeException)
   at Registrar.DynamicRegistrar.GetMethodNoThrow(Type original_type, Type type, String selector, Boolean is_static)
   at Registrar.DynamicRegistrar.GetMethodNoThrow(Type original_type, Type type, String selector, Boolean is_static)
   at Registrar.DynamicRegistrar.GetMethodNoThrow(Type original_type, Type type, String selector, Boolean is_static)
   at Registrar.DynamicRegistrar.GetMethodNoThrow(Type original_type, Type type, String selector, Boolean is_static)
   at Registrar.DynamicRegistrar.GetMethodDescriptionAndObject(Type type, IntPtr selector, Boolean is_static, IntPtr obj, IntPtr& mthis, IntPtr desc)
   at ObjCRuntime.Runtime.GetMethodAndObjectForSelector(IntPtr klass, IntPtr sel, SByte is_static, IntPtr obj, IntPtr* mthisPtr, IntPtr desc)
   at ObjCRuntime.Runtime.get_method_and_object_for_selector(IntPtr cls, IntPtr sel, SByte is_static, IntPtr obj, IntPtr* mthis, IntPtr desc, IntPtr* exception_gchandle)

=================================================================
	Native Crash Reporting
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Native stacktrace:
=================================================================
	0x10d058774 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : mono_dump_native_crash_info
	0x10cffca8e - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : mono_handle_native_crash
	0x10d206e18 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : sigabrt_signal_handler.cold.1
	0x10d0580a8 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : sigabrt_signal_handler
	0x1212655ed - /usr/lib/system/libsystem_platform.dylib : _sigtramp
	0x6a - Unknown
	0x120e2ae58 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libsystem_c.dylib : abort
	0x10bd5d1b7 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libxamarin-dotnet-debug.dylib : xamarin_unhandled_exception_handler
	0x10ce378d5 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : mono_invoke_unhandled_exception_hook
	0x10cffc695 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : mono_handle_exception_internal
	0x10cffa6a5 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : mono_handle_exception
	0x10d052889 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : mono_amd64_throw_exception
	0x14ff9c5b0 - Unknown
	0x10bd5ceb6 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libxamarin-dotnet-debug.dylib : xamarin_process_managed_exception
	0x10bd5cc7b - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libxamarin-dotnet-debug.dylib : xamarin_process_managed_exception_gchandle
	0x10bd69dd3 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libxamarin-dotnet-debug.dylib : xamarin_invoke_trampoline
	0x10bd70de9 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libxamarin-dotnet-debug.dylib : xamarin_arch_trampoline
	0x10bd71fca - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libxamarin-dotnet-debug.dylib : xamarin_x86_64_common_trampoline
	0x1112de09c - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __invoking___
	0x1112db406 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : -[NSInvocation invoke]
	0x10b912211 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/Frameworks/OneSignalCore.framework/OneSignalCore : +[SwizzlingForwarder callSelector:onObject:withArgs:]
	0x10b884542 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/Frameworks/OneSignal.framework/OneSignal : -[OneSignalAppDelegate oneSignalApplicationWillTerminate:]
	0x13272e25d - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _terminateWithStatus:]
	0x131b3f946 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[_UISceneLifecycleMultiplexer _evalTransitionToSettings:fromSettings:forceExit:withTransitionStore:]
	0x131b3f5bb - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[_UISceneLifecycleMultiplexer forceExitWithTransitionContext:scene:]
	0x132723a8a - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication workspaceShouldExit:withTransitionContext:]
	0x124259f1b - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke_2
	0x124239bfc - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSWorkspace _calloutQueue_executeCalloutFromSource:withBlock:]
	0x124259eba - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : __63-[FBSWorkspaceScenesClient willTerminateWithTransitionContext:]_block_invoke
	0x120ee40d9 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_client_callout
	0x120ee7bf2 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/usr/lib/system/libdispatch.dylib : _dispatch_block_invoke_direct
	0x124281507 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : __FBSSERIALQUEUE_IS_CALLING_OUT_TO_A_BLOCK__
	0x1242813fd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSSerialQueue _targetQueue_performNextIfPossible]
	0x12428152f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/FrontBoardServices.framework/FrontBoardServices : -[FBSSerialQueue _performNextFromRunLoopSource]
	0x111235b8f - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__
	0x111235ad1 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSource0
	0x1112352cd - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopDoSources0
	0x11122f9ba - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : __CFRunLoopRun
	0x11122f264 - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/CoreFoundation.framework/CoreFoundation : CFRunLoopRunSpecific
	0x12394b24e - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices : GSEventRunModal
	0x1327227bf - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/RuntimeRoot/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : -[UIApplication _run]
	0x1327275de - /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS.simruntime/Contents/Resources/myapp/System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore : UIApplicationMain
	0x10bd2c64a - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libxamarin-dotnet-debug.dylib : xamarin_UIApplicationMain
	0x10d06b5a9 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : do_icall
	0x10d06a0b3 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : do_icall_wrapper
	0x10d05c4af - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : interp_exec_method
	0x10d059e03 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : interp_runtime_invoke
	0x10ce7f0e8 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : mono_runtime_invoke_checked
	0x10ce870fc - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : do_exec_main_checked
	0x10cfb5ce2 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libmonosgen-2.0.dylib : mono_jit_exec
	0x10bd70c77 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/libxamarin-dotnet-debug.dylib : xamarin_main
	0x1029bf4b4 - /Users/ban/Library/Developer/CoreSimulator/Devices/10AF9E8A-5105-4C4E-ACD6-55A896E11801/data/Containers/Bundle/Application/8E36C5B4-BF50-4E49-9336-839CCD5187D9/myapp.app/myapp : main
	0x10b589384 - Unknown
	0x2030f541f - Unknown

=================================================================
	Basic Fault Address Reporting
=================================================================
Memory around native instruction pointer (0x1213031f2):0x1213031e2  ff ff c3 90 90 90 b8 48 01 00 02 49 89 ca 0f 05  .......H...I....
0x1213031f2  73 08 48 89 c7 e9 df 9a ff ff c3 90 90 90 b8 53  s.H............S
0x121303202  00 00 02 49 89 ca 0f 05 73 08 48 89 c7 e9 c7 9a  ...I....s.H.....
0x121303212  ff ff c3 90 90 90 b8 83 01 00 02 49 89 ca 0f 05  ...........I....

=================================================================
	Managed Stacktrace:
=================================================================
=================================================================
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by emawby** [comment]
@bnoffer Hello I apologize for the late response. Is this still an issue on version 5 of the SDK?

**Comment by snoova** [comment]
@emawby 
hi. 
running in the same issue using version 5.1.1

`Failed to lookup the required marshalling information.
Additional information:
	Selector: oneSignalDidRegisterForRemoteNotifications:deviceToken:
	Type: AppDelegate
'`
